version: 1
labels:
  - label: "platform"
    files:
      - "openbb_platform/.*"

  - label: "v4"
    files:
      - "openbb_platform/.*"

  - label: "bug"
    branch: "^hotfix/.*"
    files:
      - "openbb_platform/.*"

  - label: "platform"
    branch: "^hotfix/.*"
    files:
      - "openbb_platform/.*"

  - label: "enhancement"
    branch: "^feature/.*"

  - label: "bug"
    branch: "^hotfix/.*"

  - label: "docs"
    branch: "^docs/.*"
